name: Build PDF
on: [push]
jobs:
  Build-Latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Run Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
